class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // general
      'app_name': 'BRAINPACE',
      'app_subtitle': 'Tes Koran / Kraepelin Test',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'back': 'Back',
      'seconds': 's',
      'minutes': 'min',
      'on': 'On',
      'off': 'Off',

      // dashboard
      'start_test': 'START TEST',
      'latest_test': 'LATEST TEST',
      'history_logs': 'HISTORY LOGS',
      'no_history': 'No previous test logs found.',
      'clear_history': 'Clear Test History?',
      'clear_history_desc':
          'This will permanently delete all records of your tests. This action cannot be undone.',
      'delete_all': 'Delete All',
      'error_loading': 'Error loading data:',
      'tests': 'Tests',
      'solved': 'Solved',
      'accuracy': 'Accuracy',
      'consistency': 'Consistency',
      'pace': 'Pace',
      'improving': 'Improving',
      'declining': 'Declining',
      'accuracy_trend': 'Accuracy {trend} ({value}%)',
      'select_all': 'All',
      'items_selected': '{count} selected',
      'delete_selected_title': 'Delete Selected?',
      'delete_selected_msg': 'Delete {count} selected test log(s)?',
      'overview': 'Overview',
      'latest_result': 'Latest Result',
      'last_performance': 'Last Performance',
      'view_all': 'View All',
      'no_history_yet': 'No test history yet',
      'complete_test_to_see_stats': 'Complete a test to see your performance stats.',

      // instruction
      'instructions_title': 'Instructions & Practice',
      'how_to_test': 'How To Take The Test',
      'tutorial_step1': 'Sum two vertically adjacent numbers starting from the bottom up to the top.',
      'tutorial_step2': 'Take only the **last single digit** of the sum.',
      'tutorial_step2_example': 'Example: 8 + 5 = 13. Your answer is **3**.',
      'tutorial_step3': 'Every **30 seconds**, the test automatically shifts you to the next column on the right.',
      'tutorial_step4': 'Work as fast and as accurately as possible to maintain a consistent speed profile!',
      'tutorial_step_sub': 'Subtract the lower number from the upper number and take only the last digit of the result.',
      'tutorial_step_sub_example': 'Example: 8 - 5 = 3. Your answer is **3**.',
      'audio_sfx': 'Audio & SFX Check',
      'audio_desc': 'Ensure your volume is up for audio feedback.',
      'test_sound': 'Test sound',
      'interactive_calibration': 'INTERACTIVE CALIBRATION',
      'retry_practice': 'Retry practice',
      'practice_complete': 'Practice Complete!',
      'practice_complete_desc':
          'You are now fully calibrated and ready for the real cognitive test.',
      'practice_guide_add': 'Try adding the two numbers in focus. Only enter the last single digit of the result.',
      'practice_guide_sub': 'Try subtracting the bottom number from the top number. If negative, add 10 (e.g. 4 - 7 = -3 -> 7). Only enter the last single digit.',
      'active_math': 'Active Math:',
      'press_unit_digit':
          'Sum these numbers and press the unit digit ({answer}) on the numpad below.',
      'press_unit_digit_sub':
          'Subtract these numbers and press the unit digit ({answer}) on the numpad below.',
      'start_real_test': 'START REAL TEST',

      // config summary
      'test_config': 'TEST CONFIGURATION',
      'duration': 'Duration',
      'operation': 'Operation',
      'pattern': 'Pattern',
      'format': 'Format',
      'keyboard': 'Keyboard',

      // gameplay
      'sum_these_numbers': 'SUM THESE NUMBERS',
      'column': 'Column',
      'column_label': 'Column {current} / {total}',
      'next_shift': 'Next Column Shift in:',
      'column_complete': 'Column complete! Moving to next...',
      'quit_test': 'Quit Cognitive Test?',
      'quit_test_desc':
          'Exiting now will discard your current test data. Are you sure you want to quit?',
      'quit': 'Quit Test',

      // result
      'test_results': 'TEST RESULTS',
      'analysis_desc': 'Analysis of your cognitive processing profiles.',
      'total_solved': 'Total solved',
      'correct_ratio': 'Correct ratio',
      'speed_stability': 'Speed profile stability',
      'consistency_over_time': 'CONSISTENCY OVER TIME',
      'legend_total': 'Total',
      'legend_correct': 'Correct',
      'home': 'HOME',
      'test_again': 'TEST AGAIN',

      // history detail
      'detail_results': 'DETAIL RESULTS',
      'score_overview': 'SCORE OVERVIEW',
      'perf_per_column': 'PERFORMANCE PER COLUMN',
      'insights': 'INSIGHTS',
      'correct': 'Correct',
      'incorrect': 'Incorrect',
      'avg_per_min': 'Avg/Min',
      'ans_label': 'Ans',
      'cor_label': 'Cor',
      'average_pace': 'Average Pace',
      'peak_performance': 'Peak',
      'slowest_column': 'Slowest',
      'best_accuracy': 'Best Accuracy',
      'trend': 'Trend',
      'answers_col': '/col',
      'answers': 'answers',

      // settings
      'settings': 'SETTINGS',
      'feedback': 'FEEDBACK',
      'display': 'DISPLAY',
      'data': 'DATA',
      'sound_effects': 'Sound Effects',
      'sound_desc': 'Audio feedback for correct/incorrect answers',
      'vibration': 'Vibration',
      'vibration_desc': 'Haptic feedback on answer input',
      'animations': 'Animations',
      'animations_desc': 'Enable smooth UI transitions',
      'reset_data': 'Reset All Data',
      'reset_data_desc': 'Permanently delete all test history and scores',
      'reset_confirm_title': 'Reset All Data?',
      'reset_confirm_desc':
          'This will permanently delete all test history and scores. This action cannot be undone.',
      'reset': 'Reset',
      'reset_snackbar': 'All data has been reset.',
      'language': 'Language',
      'language_desc': 'Choose your preferred language',
      'timer_duration': 'Timer Duration',
      'timer_desc': 'Set duration for each test session',
      'operation_type': 'Operation Type',
      'addition': 'Addition',
      'subtraction': 'Subtraction',
      'mixed': 'Mixed',
      'pattern_type': 'Pattern Type',
      'sequential': 'Sequential',
      'random': 'Random',
      'display_format': 'Display Format',
      'horizontal': 'Horizontal',
      'vertical': 'Vertical',
      'keyboard_layout': 'Keyboard Layout',
      'ascending': '1-2-3',
      'calculator': '7-8-9',
      'mode_settings': 'MODE SETTINGS',
      'player_name_title': 'Enter Your Name',
      'player_name_desc': 'Enter a name to identify this test result in your history.',
      'player_name_hint': 'Your name...',
      'skip': 'Skip',
    },
    'id': {
      // general
      'app_name': 'BRAINPACE',
      'app_subtitle': 'Tes Koran / Kraepelin Test',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'confirm': 'Konfirmasi',
      'back': 'Kembali',
      'seconds': 'd',
      'minutes': 'mnt',
      'on': 'Aktif',
      'off': 'Nonaktif',

      // dashboard
      'start_test': 'MULAI TES',
      'latest_test': 'TES TERAKHIR',
      'history_logs': 'RIWAYAT',
      'no_history': 'Belum ada riwayat tes.',
      'clear_history': 'Hapus Riwayat Tes?',
      'clear_history_desc':
          'Ini akan menghapus permanen semua catatan tes. Tindakan ini tidak bisa dibatalkan.',
      'delete_all': 'Hapus Semua',
      'error_loading': 'Gagal memuat data:',
      'tests': 'Tes',
      'solved': 'Terjawab',
      'accuracy': 'Akurasi',
      'consistency': 'Konsistensi',
      'pace': 'Kecepatan',
      'improving': 'Meningkat',
      'declining': 'Menurun',
      'accuracy_trend': 'Akurasi {trend} ({value}%)',
      'select_all': 'Pilih Semua',
      'items_selected': '{count} dipilih',
      'delete_selected_title': 'Hapus Terpilih?',
      'delete_selected_msg': 'Hapus {count} riwayat tes yang dipilih?',
      'overview': 'Ikhtisar',
      'latest_result': 'Hasil Terakhir',
      'last_performance': 'Performa Terakhir',
      'view_all': 'Lihat Semua',
      'no_history_yet': 'Belum ada riwayat tes',
      'complete_test_to_see_stats': 'Selesaikan tes untuk melihat statistik performa Anda.',

      // instruction
      'instructions_title': 'Instruksi & Latihan',
      'how_to_test': 'Cara Mengikuti Tes',
      'tutorial_step1': 'Jumlahkan dua angka yang berdekatan secara vertikal dari bawah ke atas.',
      'tutorial_step2': 'Ambil hanya **satu digit terakhir** dari hasil penjumlahan.',
      'tutorial_step2_example': 'Contoh: 8 + 5 = 13. Jawaban Anda adalah **3**.',
      'tutorial_step3': 'Setiap **30 detik**, tes akan otomatis berpindah ke kolom berikutnya di sebelah kanan.',
      'tutorial_step4': 'Bekerjalah secepat dan setepat mungkin untuk menjaga profil kecepatan yang konsisten!',
      'tutorial_step_sub': 'Kurangkan angka bawah dari angka atas dan ambil digit terakhir dari hasilnya.',
      'tutorial_step_sub_example': 'Contoh: 8 - 5 = 3. Jawaban Anda adalah **3**.',
      'audio_sfx': 'Cek Audio & SFX',
      'audio_desc': 'Pastikan volume Anda menyala untuk umpan balik suara.',
      'test_sound': 'Tes suara',
      'interactive_calibration': 'KALIBRASI INTERAKTIF',
      'retry_practice': 'Ulangi latihan',
      'practice_complete': 'Latihan Selesai!',
      'practice_complete_desc': 'Anda sekarang siap untuk tes kognitif yang sesungguhnya.',
      'practice_guide_add': 'Jumlahkan dua angka yang menjadi fokus. Hanya masukkan digit satuan terakhir dari hasilnya.',
      'practice_guide_sub': 'Kurangkan angka atas dengan angka bawah. Jika hasilnya negatif, tambahkan 10 (misal: 4 - 7 = -3 -> 7). Hanya masukkan digit satuan terakhir.',
      'active_math': 'Matematika Aktif:',
      'press_unit_digit':
          'Jumlahkan angka-angka ini dan tekan digit terakhir ({answer}) pada papan tombol di bawah.',
      'press_unit_digit_sub':
          'Kurangkan angka-angka ini dan tekan digit terakhir ({answer}) pada papan tombol di bawah.',
      'start_real_test': 'MULAI TES',

      // config summary
      'test_config': 'KONFIGURASI TES',
      'duration': 'Durasi',
      'operation': 'Operasi',
      'pattern': 'Pola',
      'format': 'Format',
      'keyboard': 'Keyboard',

      // gameplay
      'sum_these_numbers': 'JUMLAHKAN ANGKA INI',
      'column': 'Kolom',
      'column_label': 'Kolom {current} / {total}',
      'next_shift': 'Pergeseran Kolom dalam:',
      'column_complete': 'Kolom selesai! Pindah ke kolom berikutnya...',
      'quit_test': 'Keluar dari Tes?',
      'quit_test_desc': 'Keluar sekarang akan menghapus data tes saat ini. Apakah Anda yakin?',
      'quit': 'Keluar',

      // result
      'test_results': 'HASIL TES',
      'analysis_desc': 'Analisis profil pemrosesan kognitif Anda.',
      'total_solved': 'Total terjawab',
      'correct_ratio': 'Rasio benar',
      'speed_stability': 'Stabilitas kecepatan',
      'consistency_over_time': 'KONSISTENSI DARI WAKTU KE WAKTU',
      'legend_total': 'Total',
      'legend_correct': 'Benar',
      'home': 'BERANDA',
      'test_again': 'TES LAGI',

      // history detail
      'detail_results': 'HASIL DETAIL',
      'score_overview': 'RINGKASAN SKOR',
      'perf_per_column': 'PERFORMA PER KOLOM',
      'insights': 'WAWASAN',
      'correct': 'Benar',
      'incorrect': 'Salah',
      'avg_per_min': 'Rata/mnt',
      'ans_label': 'Jwb',
      'cor_label': 'Bnr',
      'average_pace': 'Kecepatan Rata-rata',
      'peak_performance': 'Puncak',
      'slowest_column': 'Terlambat',
      'best_accuracy': 'Akurasi Terbaik',
      'trend': 'Tren',
      'answers_col': '/kolom',
      'answers': 'jawaban',

      // settings
      'settings': 'PENGATURAN',
      'feedback': 'UMPAN BALIK',
      'display': 'TAMPILAN',
      'data': 'DATA',
      'sound_effects': 'Efek Suara',
      'sound_desc': 'Umpan balik suara untuk jawaban benar/salah',
      'vibration': 'Getaran',
      'vibration_desc': 'Umpan balik getaran saat input jawaban',
      'animations': 'Animasi',
      'animations_desc': 'Aktifkan transisi UI yang halus',
      'reset_data': 'Reset Semua Data',
      'reset_data_desc': 'Hapus permanen semua riwayat tes dan skor',
      'reset_confirm_title': 'Reset Semua Data?',
      'reset_confirm_desc': 'Ini akan menghapus permanen semua riwayat tes. Tindakan ini tidak bisa dibatalkan.',
      'reset': 'Reset',
      'reset_snackbar': 'Semua data telah direset.',
      'language': 'Bahasa',
      'language_desc': 'Pilih bahasa yang Anda inginkan',
      'timer_duration': 'Durasi Waktu',
      'timer_desc': 'Atur durasi untuk setiap sesi tes',
      'operation_type': 'Jenis Operasi',
      'addition': 'Penjumlahan',
      'subtraction': 'Pengurangan',
      'mixed': 'Campuran',
      'pattern_type': 'Tipe Pola',
      'sequential': 'Berurut',
      'random': 'Acak',
      'display_format': 'Format Tampilan',
      'horizontal': 'Horizontal',
      'vertical': 'Vertikal',
      'keyboard_layout': 'Tata Letak Keyboard',
      'ascending': '1-2-3',
      'calculator': '7-8-9',
      'mode_settings': 'PENGATURAN MODE',
      'player_name_title': 'Masukkan Nama Anda',
      'player_name_desc': 'Masukkan nama untuk mengidentifikasi hasil tes ini di riwayat Anda.',
      'player_name_hint': 'Nama Anda...',
      'skip': 'Lewati',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final template = _translations[languageCode]?[key] ?? _translations['en']?[key] ?? key;
    if (params == null) return template;
    return _interpolate(template, params);
  }

  String _interpolate(String template, Map<String, String> params) {
    String result = template;
    params.forEach((key, value) {
      result = result.replaceAll('{$key}', value);
    });
    return result;
  }

  static List<String> get supportedLanguages => ['en', 'id'];
  static List<String> get languageNames => ['English', 'Bahasa Indonesia'];
}
